

/* =====================================================
   PRACTICE MODE (STUDENT) — AI READY
===================================================== */

/* ================= PAGE GUARD ================= */
const token = localStorage.getItem("studentToken");

if (!token) {
  // window.location.href = "/frontend/pages/student-login.html";
}

/* ================= STORAGE ================= */
const mockExams =
  JSON.parse(localStorage.getItem("mockExams")) || [];

/* ================= CONTEXT ================= */
const activeExamId =
  Number(localStorage.getItem("activeMockExamId"));

const exam = mockExams.find(e => e.id === activeExamId);

if (!exam) {
  alert("No practice exam found.");
  window.location.href = "/frontend/pages/mock-exams.html";
}

/* ================= DOM ================= */
const practiceTitle = document.getElementById("practiceTitle");
const container = document.getElementById("practiceContainer");

/* ================= RENDER ================= */
practiceTitle.textContent = `Practice — ${exam.title}`;
container.innerHTML = "";

/* ================= QUESTIONS ================= */
exam.questions.forEach((q, index) => {
  const block = document.createElement("div");
  block.className = "practice-question";

  block.innerHTML = `
    <h3>Question ${index + 1}</h3>
    <p>${q.question}</p>

    ${q.options.map((opt, i) => `
      <button class="practice-option" data-index="${i}">
        ${opt}
      </button>
    `).join("")}

    <p class="practice-feedback" hidden></p>

    <div class="practice-explanation" hidden>
      <strong>Explanation:</strong>
      <p>
        This explanation will be generated by the AI assistant
        to help you understand the correct concept behind the question.
      </p>
    </div>
  `;

  const buttons = block.querySelectorAll(".practice-option");
  const feedback = block.querySelector(".practice-feedback");
  const explanation = block.querySelector(".practice-explanation");

  buttons.forEach(btn => {
    btn.onclick = () => {
      const selected = Number(btn.dataset.index);

      if (selected === q.correctIndex) {
        feedback.textContent = "✅ Correct!";
        feedback.style.color = "green";
      } else {
        feedback.textContent =
          `❌ Wrong. Correct answer: ${q.options[q.correctIndex]}`;
        feedback.style.color = "red";
      }

      feedback.hidden = false;
      explanation.hidden = false;
    };
  });

  container.appendChild(block);
});

